ports:
  - port: 6005
    onOpen: ignore
  - port: 8080
    onOpen: open-preview

tasks:
  - init: yarn
    command: yarn run dev
    
vscode:
  extensions:
    - scrimba.vsimba@2.1.1:VOA20iAD+RG3yMfe73k32Q==
